channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.0.2
  - pip:
    - dipy==1.0.0
    - pytest
    - cython==0.29
    - numpy==1.9.0
    - scipy==1.0
    - nibabel==2.4.0
    - h5py==2.4.0