channels:
  - conda-forge
dependencies:
  - python=3.5.5
  - pip=20.3.4
  - pip:
      - setuptools==50.3.2
      - numpy==1.13.3
      - scipy==0.19.0
      - scikit-learn==0.22.2.post1
      - joblib==0.12.0
      - nibabel==2.0.2
      - pytest==5.4.2
      - matplotlib==3.0.3
install_repo: True