channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=20.0.2
  - pip:
      - joblib>=1.0.0
      - lxml
      - nibabel>=3.2.0
      - numpy>=1.19.0
      - pandas>=1.1.5
      - requests>=2.25.0
      - scikit-learn>=1.0.0
      - scipy>=1.6.0
      - packaging
      - matplotlib>=3.3.0
install_repo: True