channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=20.0.2
  - pip:
      - joblib>=0.15
      - lxml
      - nibabel>=3.0.0
      - numpy>=1.18
      - pandas>=1.0
      - requests>=2
      - scikit-learn>=0.22
      - scipy>=1.5
install_repo: True