channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=20.0.2
  - pip:
      - setuptools
      - numpy>=1.16
      - scipy>=1.2
      - scikit-learn>=0.21
      - joblib>=0.12
      - nibabel>=2.5
      - pandas>=0.24
install_repo: True