channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=20.0.2
  - pip:
      - setuptools
      - numpy>=1.18
      - scipy>=1.5
      - scikit-learn>=0.22
      - joblib>=0.15
      - nibabel>=3.0
      - pandas>=1.0
install_repo: True