channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=20.0.2
  - setuptools=65.3.0
  - pip:
      - numpy>=1.6.2
      - scipy>=0.11
      - networkx>=1.7
      - traits>=4.3
      - python-dateutil>=1.5
      - nibabel>=2.0.1
      - nose>=1.2
      - future==0.15.2
      - simplejson>=3.8.0
      - prov>=1.4.0
      - xvfbwrapper
      - psutil
      - funcsigs
      - configparser
install_repo: True